require("dotenv").config();


const AWS_DATABASE = "aws-final"
const AWS_DATABASE_USER = "admin"
const AWS_DATABASE_PASSWORD = "danielAwsfinal"
const AWS_DATABASE_HOST = "aws-final.cxpc0lkexnnd.us-east-1.rds.amazonaws.com"
const AWS_DIALECT = "mysql"
const AWS_S3BUCKET = "aws-final-img"
const AWS_S3ACL = "public-read"

const AWS_ACCESS_KEY_ID = "ASIASWGYFLKVE6BVDZVN"
const AWS_SECRET_ACCESS_KEY = "jHP0op5kR+AgKk5/VpP6P5VhLb2EaDhKTt/lZ4tW"
const AWS_SESSION_TOKEN = "FwoGZXIvYXdzEK7//////////wEaDHLY4t0+woKSViHp5CLMAYItlnYpLmrsdgxwirHwbNCNOV8eNy3q48byRz993ouVnx0hLbxy2oICfBXgG7tVwGJYRtuSR9WFUzSQHwPWvX3yg4bGQH6/gKN7tv/KEDIun6idZ9kiFJZ/azEw1+86kwbGK3dVTqgtHta6ohiUG4kvbb7q8C6/23GWxyVhKTiFdMkFId+c4TfTLE5V7qN6Y8sVbdJV/WyqqKBSesHXUM0JlGl75Mhzra5NU7vdnnI31J3TnkOT2k86cO4pOMdCjPScXTwIbRPVPujlJyi7xOOcBjItAzz7rs2m4KhQG7qmqtkummkdWhEbS7M0ybp3gVXei8Baybw67695TWZDNLB1"
const AWS_REGION = "us-east-1"

const PORT = 8080;
const DATABASE = AWS_DATABASE
const DATABASEUSER = AWS_DATABASE_USER
const DATABASEPASSWORD = AWS_DATABASE_PASSWORD
const DATABASEHOST = AWS_DATABASE_HOST
const DATABASEDIALECT = AWS_DIALECT
const S3BUCKET = AWS_S3BUCKET
const S3ACL = AWS_S3ACL
const S3ACCESSKEYID = AWS_ACCESS_KEY_ID
const S3SECRETACCESSKEY = AWS_SECRET_ACCESS_KEY
const S3SESSIONTOKEN = AWS_SESSION_TOKEN
const S3REGION = AWS_REGION


module.exports = {
    PORT,
    DATABASE,
    DATABASEUSER,
    DATABASEPASSWORD,
    DATABASEHOST,
    DATABASEDIALECT,
    S3BUCKET,
    S3ACL,
    S3ACCESSKEYID,
    S3SECRETACCESSKEY,
    S3SESSIONTOKEN,
    S3REGION,
};